import { useState, useEffect } from 'react';
import { useForm, useWatch } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { format } from 'date-fns';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { Receipt, CalendarIcon, X, Upload } from 'lucide-react';
import type { Receipt as ReceiptType, Estimate, TaxProvince } from '@/types';
import { PAYMENT_TYPES } from '@/types';

const receiptSchema = z.object({
  vendor_ref: z.string().min(1, 'Vendor reference is required'),
  date: z.date(),
  subtotal: z.number().min(0, 'Amount must be positive'),
  gst_amount: z.number().min(0),
  pst_amount: z.number().min(0),
  total: z.number().min(0),
  payment_type: z.string().optional(),
  estimate_id: z.string().optional(),
  notes: z.string().optional(),
  tags: z.array(z.string()),
});

type ReceiptFormData = z.infer<typeof receiptSchema>;

interface ReceiptFormDialogProps {
  vendorId: string;
  vendorType: 'contract' | 'retail';
  taxProvince: TaxProvince;
  estimates?: Estimate[];
  receipt?: ReceiptType;
  preSelectedEstimateId?: string;
  onSubmit: (data: Omit<ReceiptType, 'id' | 'display_id' | 'project_id' | 'vendor_id' | 'created_at' | 'updated_at' | 'status' | 'created_by' | 'tax_total'>, file?: File | null) => void;
  trigger?: React.ReactNode;
}

export function ReceiptFormDialog({
  vendorId,
  vendorType,
  taxProvince,
  estimates = [],
  receipt,
  preSelectedEstimateId,
  onSubmit,
  trigger
}: ReceiptFormDialogProps) {
  const [open, setOpen] = useState(false);
  const [dateOpen, setDateOpen] = useState(false);
  const [tagInput, setTagInput] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  
  const form = useForm<ReceiptFormData>({
    resolver: zodResolver(receiptSchema),
    defaultValues: receipt ? {
      vendor_ref: receipt.vendor_ref || '',
      date: new Date(receipt.date),
      subtotal: receipt.subtotal,
      gst_amount: receipt.gst_amount,
      pst_amount: receipt.pst_amount,
      total: receipt.total,
      payment_type: receipt.payment_type || '',
      estimate_id: receipt.estimate_id || '',
      notes: receipt.notes || '',
      tags: receipt.tags || [],
    } : {
      vendor_ref: '',
      date: new Date(),
      subtotal: 0,
      gst_amount: 0,
      pst_amount: 0,
      total: 0,
      payment_type: '',
      estimate_id: preSelectedEstimateId || '',
      notes: '',
      tags: [],
    },
  });
  
  // Auto-calculate total when tax amounts change
  const subtotal = useWatch({ control: form.control, name: 'subtotal' });
  const gstAmount = useWatch({ control: form.control, name: 'gst_amount' });
  const pstAmount = useWatch({ control: form.control, name: 'pst_amount' });
  
  useEffect(() => {
    const total = (subtotal || 0) + (gstAmount || 0) + (pstAmount || 0);
    form.setValue('total', total);
  }, [subtotal, gstAmount, pstAmount, form]);
  
  const handleSubmit = (data: ReceiptFormData) => {
    console.log('Receipt form submitting:', data);
    console.log('estimate_id from form:', data.estimate_id);
    const submitData = {
      ...data,
      vendor_id: vendorId,
      estimate_id: data.estimate_id || undefined,
      date: format(data.date, 'yyyy-MM-dd'),
      // tax_total is generated by database - don't include it
    };
    console.log('Submitting to parent:', submitData);
    onSubmit(submitData as Omit<ReceiptType, 'id' | 'display_id' | 'project_id' | 'vendor_id' | 'created_at' | 'updated_at' | 'status' | 'created_by' | 'tax_total'>, selectedFile);
    setOpen(false);
    form.reset();
    setSelectedFile(null);
  };
  
  const addTag = () => {
    if (tagInput.trim() && !form.getValues('tags').includes(tagInput.trim())) {
      form.setValue('tags', [...form.getValues('tags'), tagInput.trim().toLowerCase()]);
      setTagInput('');
    }
  };
  
  const removeTag = (tag: string) => {
    form.setValue('tags', form.getValues('tags').filter((t) => t !== tag));
  };
  
  const taxLabels = {
    ON: { gst: 'HST (Federal 5%)', pst: 'HST (Provincial 8%)' },
    QC: { gst: 'GST (5%)', pst: 'QST (9.975%)' },
  };
  
  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger>
        {trigger || (
          <Button variant="outline" size="sm">
            <Receipt className="h-4 w-4 mr-2" />
            Add Receipt
          </Button>
        )}
      </DialogTrigger>
      
      <DialogContent className="max-w-5xl max-h-[95vh] overflow-y-auto p-8">
        <DialogHeader className="mb-6">
          <DialogTitle className="text-xl">
            {receipt ? 'Edit Receipt' : 'Add New Receipt'}
          </DialogTitle>
          <DialogDescription className="text-base mt-2">
            {receipt
              ? 'Update the receipt details below.'
              : 'Enter the receipt information.'}
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={form.handleSubmit(handleSubmit)} className="space-y-8">
          {/* Section: Basic Info */}
          <div className="space-y-4">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Basic Information</h3>
            <div className="grid grid-cols-2 gap-5">
            <div className="space-y-2">
              <Label htmlFor="vendor_ref">Vendor Reference/Invoice # *</Label>
              <Input
                id="vendor_ref"
                {...form.register('vendor_ref')}
                placeholder="e.g., INV-2026-001"
                className="h-11"
              />
              {form.formState.errors.vendor_ref && (
                <p className="text-sm text-destructive mt-1">{form.formState.errors.vendor_ref.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label>Date *</Label>
              <Popover open={dateOpen} onOpenChange={setDateOpen}>
                <PopoverTrigger>
                  <Button
                    type="button"
                    variant="outline"
                    className={cn(
                      "w-full justify-start text-left font-normal h-11",
                      !form.watch('date') && "text-muted-foreground"
                    )}
                  >
                    <CalendarIcon className="mr-2 h-4 w-4" />
                    {form.watch('date') ? format(form.watch('date'), 'PPP') : "Pick a date"}
                  </Button>
                </PopoverTrigger>
                <PopoverContent className="w-auto p-0" align="start">
                  <Calendar
                    mode="single"
                    selected={form.watch('date')}
                    onSelect={(date) => {
                      form.setValue('date', date || new Date());
                      setDateOpen(false);
                    }}
                    initialFocus
                  />
                </PopoverContent>
              </Popover>
            </div>
            </div>
          </div>

          {/* Section: Financial */}
          <div className="space-y-4 pt-4 border-t">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Financial Details</h3>
            <div className="grid grid-cols-4 gap-5">
            <div className="space-y-2">
              <Label htmlFor="subtotal">Subtotal (CAD) *</Label>
              <Input
                id="subtotal"
                type="number"
                step="0.01"
                {...form.register('subtotal', { valueAsNumber: true })}
                placeholder="0.00"
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="gst_amount">{taxLabels[taxProvince].gst}</Label>
              <Input
                id="gst_amount"
                type="number"
                step="0.01"
                {...form.register('gst_amount', { valueAsNumber: true })}
                placeholder="0.00"
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="pst_amount">{taxLabels[taxProvince].pst}</Label>
              <Input
                id="pst_amount"
                type="number"
                step="0.01"
                {...form.register('pst_amount', { valueAsNumber: true })}
                placeholder="0.00"
                className="h-11"
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="total">Total (CAD)</Label>
              <Input
                id="total"
                type="number"
                step="0.01"
                {...form.register('total', { valueAsNumber: true })}
                readOnly
                className="bg-muted h-11 font-semibold"
              />
            </div>
            </div>
          </div>

          {/* Section: Linking */}
          <div className="space-y-4 pt-4 border-t">
            <h3 className="text-sm font-medium text-muted-foreground uppercase tracking-wide">Additional Information</h3>
            <div className="grid grid-cols-2 gap-5">
            <div className="space-y-2">
              <Label htmlFor="payment_type">Payment Type</Label>
              <Select
                value={form.watch('payment_type') || undefined}
                onValueChange={(value) => form.setValue('payment_type', value || undefined)}
              >
                <SelectTrigger className="h-11">
                  <SelectValue placeholder="Select type" />
                </SelectTrigger>
                <SelectContent>
                  {PAYMENT_TYPES.map((type) => (
                    <SelectItem key={type.value} value={type.value}>
                      {type.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {vendorType === 'contract' && estimates.length > 0 && (
              <div className="space-y-2">
                <Label htmlFor="estimate_id">Link to Estimate</Label>
                <Select
                  value={form.watch('estimate_id') || undefined}
                  onValueChange={(value) => form.setValue('estimate_id', value || undefined)}
                >
                  <SelectTrigger className="h-11">
                    <SelectValue placeholder="Select estimate (optional)" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="">None (unlinked)</SelectItem>
                    {estimates.map((estimate) => (
                      <SelectItem key={estimate.id} value={estimate.id}>
                        {estimate.display_id} - {estimate.title}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
            )}
            </div>
          </div>

          {/* Section: Tags */}
          <div className="space-y-4 pt-4 border-t">
            <div className="space-y-2">
              <Label htmlFor="tags">Tags</Label>
              <div className="flex gap-2">
                <Input
                  id="tags"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      addTag();
                    }
                  }}
                  placeholder="Add a tag and press Enter"
                  className="h-11"
                />
                <Button type="button" variant="outline" onClick={addTag} className="h-11 px-6">
                  Add
                </Button>
              </div>
              {form.getValues('tags').length > 0 && (
                <div className="flex flex-wrap gap-2 mt-3">
                  {form.getValues('tags').map((tag) => (
                    <Badge key={tag} variant="secondary" className="gap-1 px-3 py-1 text-sm">
                      {tag}
                      <button
                        type="button"
                        onClick={() => removeTag(tag)}
                        className="hover:text-destructive ml-1"
                      >
                        <X className="h-3 w-3" />
                      </button>
                    </Badge>
                  ))}
                </div>
              )}
            </div>
            </div>

          {/* Section: Notes */}
          <div className="space-y-4 pt-4 border-t">
            <div className="space-y-2">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                {...form.register('notes')}
                placeholder="Any additional details..."
                rows={4}
                className="resize-none"
              />
            </div>
            </div>

          {/* Section: Document Upload */}
          <div className="space-y-4 pt-4 border-t">
            <div className="space-y-2">
              <Label>Attach Document</Label>
              <div className="border-2 border-dashed border-muted-foreground/25 rounded-xl p-8 text-center bg-muted/30 hover:bg-muted/50 transition-colors">
                <Upload className="h-10 w-10 mx-auto mb-3 text-muted-foreground" />
                <p className="text-sm font-medium mb-1">
                  {selectedFile ? selectedFile.name : 'Drag and drop or click to upload'}
                </p>
                <p className="text-xs text-muted-foreground mb-4">PDF, JPG, or PNG up to 10MB</p>
                <Input
                  type="file"
                  accept="image/*,.pdf"
                  onChange={(e) => setSelectedFile(e.target.files?.[0] || null)}
                  className="hidden"
                  id="file-upload"
                />
                <Button type="button" variant="outline" size="sm" className="h-9 px-4">
                  <label htmlFor="file-upload" className="cursor-pointer">
                    Select File
                  </label>
                </Button>
              </div>
            </div>
          </div>

          <DialogFooter className="gap-3 pt-4">
            <Button type="button" variant="outline" onClick={() => setOpen(false)} className="h-11 px-6">
              Cancel
            </Button>
            <Button type="submit" className="h-11 px-6">
              {receipt ? 'Update Receipt' : 'Create Receipt'}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
